# Generated by Django 4.1.7 on 2023-04-17 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_name_student_badge_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Student", new_name="OPSEmp",),
    ]
